/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.SysAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author cyyo
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form adminManagementJPanel
     */
        JPanel userProcessContainer;
        EcoSystem ecoSystem;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageNetworkBtn = new javax.swing.JButton();
        ManageEnterpriseBtn = new javax.swing.JButton();
        ManageEnterpriseAdminBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        ManageNetworkBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ManageNetworkBtn.setForeground(new java.awt.Color(102, 51, 0));
        ManageNetworkBtn.setText("Manage Network");
        ManageNetworkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageNetworkBtnActionPerformed(evt);
            }
        });

        ManageEnterpriseBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ManageEnterpriseBtn.setForeground(new java.awt.Color(102, 0, 0));
        ManageEnterpriseBtn.setText("Manage Enterprise");
        ManageEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEnterpriseBtnActionPerformed(evt);
            }
        });

        ManageEnterpriseAdminBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ManageEnterpriseAdminBtn.setForeground(new java.awt.Color(102, 0, 0));
        ManageEnterpriseAdminBtn.setText("Manage Enterprise Admin");
        ManageEnterpriseAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEnterpriseAdminBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Welcome to our system！");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ManageEnterpriseAdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManageNetworkBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManageEnterpriseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(ManageNetworkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(ManageEnterpriseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(ManageEnterpriseAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ManageNetworkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageNetworkBtnActionPerformed
        // TODO add your handling code here:
        ManageNetworkJPanel manageNetworkJPanel=new ManageNetworkJPanel(userProcessContainer, ecoSystem);
        userProcessContainer.add("manageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageNetworkBtnActionPerformed

    private void ManageEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEnterpriseBtnActionPerformed
        // TODO add your handling code here:
        
        if(ecoSystem.getNetworkList().size() == 0){
            JOptionPane.showMessageDialog(null, "No Network Created Yet!");
        }else{
            ManageEnterpriseJPanel manageEnterpriseJPanel =new ManageEnterpriseJPanel(userProcessContainer, ecoSystem);
            userProcessContainer.add("manageNetworkJPanel",manageEnterpriseJPanel);
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_ManageEnterpriseBtnActionPerformed

    private void ManageEnterpriseAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEnterpriseAdminBtnActionPerformed
        // TODO add your handling code here:
        boolean checkEnterpriseNotEmpty = false;
        for(Network network : ecoSystem.getNetworkList())
            if(network.getEnterpriseDirectory().getEnterpriseList().size() > 0)
                checkEnterpriseNotEmpty = true;
        if(checkEnterpriseNotEmpty){
            ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel =new ManageEnterpriseAdminJPanel(userProcessContainer, ecoSystem);
            userProcessContainer.add("manageNetworkJPanel",manageEnterpriseAdminJPanel);
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_ManageEnterpriseAdminBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageEnterpriseAdminBtn;
    private javax.swing.JButton ManageEnterpriseBtn;
    private javax.swing.JButton ManageNetworkBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
