/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.Librarian;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.LibrarianOrganization;
import Business.Organization.StudentOrganization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author cyyo
 */
public class LibrarianWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel container;
    private UserAccount account;
    private LibrarianOrganization organization;
    private Enterprise enterprise;
    
    /**
     * Creates new form LibrarianManagementJPanel
     */
    public LibrarianWorkAreaJPanel(JPanel container, UserAccount account, LibrarianOrganization organization, Enterprise enterprise) {
        this.container = container;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        booksViewBtn = new javax.swing.JButton();
        checkBooksBtn1 = new javax.swing.JButton();
        rentingProcessjButton = new javax.swing.JButton();

        jLabel1.setText("Please manage the library system");

        booksViewBtn.setText(" books View");
        booksViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksViewBtnActionPerformed(evt);
            }
        });

        checkBooksBtn1.setText("Renting History");
        checkBooksBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBooksBtn1ActionPerformed(evt);
            }
        });

        rentingProcessjButton.setText("Renting In Process");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rentingProcessjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkBooksBtn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(booksViewBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(139, 139, 139))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(booksViewBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rentingProcessjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBooksBtn1)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void booksViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksViewBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booksViewBtnActionPerformed

    private void checkBooksBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBooksBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBooksBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton booksViewBtn;
    private javax.swing.JButton checkBooksBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton rentingProcessjButton;
    // End of variables declaration//GEN-END:variables
}
