/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.Librarian;

import Business.Book.Book;
import Business.Coffee.Coffee;
import Business.Enterprise.LibraryEnterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BookRequest;
import Business.WorkQueue.CoffeeQueue;
import Business.WorkQueue.CoffeeRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;


/**
 *
 * @author cyyo
 */
public class AnalysisJPanel extends javax.swing.JPanel {
    private LibraryEnterprise enterprise;
    private JPanel container;
    /**
     * Creates new form bookRecordJPanel
     */
    public AnalysisJPanel(JPanel container, LibraryEnterprise enterprise) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        popBookButton = new javax.swing.JButton();
        popStuButton = new javax.swing.JButton();
        popCoffeeButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        popBookButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        popBookButton.setForeground(new java.awt.Color(102, 0, 0));
        popBookButton.setText("Check the top 5 popular Book");
        popBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popBookButtonActionPerformed(evt);
            }
        });

        popStuButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        popStuButton.setForeground(new java.awt.Color(102, 0, 51));
        popStuButton.setText("Check the top 5 active Student");
        popStuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popStuButtonActionPerformed(evt);
            }
        });

        popCoffeeButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        popCoffeeButton.setForeground(new java.awt.Color(102, 0, 51));
        popCoffeeButton.setText("Check the top 5 popular Coffee");
        popCoffeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popCoffeeButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("一 一 一 一 一 一 一 一 一 一 一 一 一  一 一 一 一 一 一 一 一 ");

        jLabel8.setText("一 一 一 一 一 一 一 一 一 一 一 一 一  一 一 一 一 一 一 一 一 ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(popBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(popCoffeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(popStuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(popBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(popStuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(popCoffeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void popStuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popStuButtonActionPerformed
        // TODO add your handling code here:
        
        HashMap<String, Integer> stuRank = new HashMap();
        
        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(organization.getName().equals("Student Organization"))
                for(UserAccount ua : organization.getUserAccountDirectory().getUserAccountList())
                    stuRank.put(ua.getPerson().getName(), 0);
        }
        
        for(BookRequest bookRequest : enterprise.getBookQueue().getBookRequestList()){
            int count = 0;
            if(stuRank.containsKey(bookRequest.getSender().getPerson().getName()))
                count = stuRank.get(bookRequest.getSender().getPerson().getName());
            count ++;
            stuRank.put(bookRequest.getSender().getPerson().getName(), count);
        }
        
        ArrayList<Map.Entry<String, Integer>> rankList = new ArrayList(stuRank.entrySet());
        
        Collections.sort(rankList, new Comparator<Map.Entry<String, Integer>>() {

            @Override
            public int compare(Map.Entry<String, Integer> o1, Map.Entry<String, Integer> o2) {
                return -o1.getValue()+o2.getValue();
            }
        });
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for(int i = 0; i< 3; i++){
            dataset.setValue(rankList.get(i).getValue(), "a", rankList.get(i).getKey());
        }
        JFreeChart chart = ChartFactory.createBarChart("Book Borrow", "Student Name", "Number", dataset, PlotOrientation.VERTICAL , false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame chartFrame = new ChartFrame("Student Active", chart);
        chartFrame.setVisible(true);
        chartFrame.setSize(600, 400);
        
    }//GEN-LAST:event_popStuButtonActionPerformed

    private void popCoffeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popCoffeeButtonActionPerformed
        // TODO add your handling code here:
        HashMap<String, Integer> coffeeRank = new HashMap();
        CoffeeQueue cq = new CoffeeQueue();
        
        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
            if(organization.getName().equals("Student Organization"))
                for(UserAccount us : organization.getUserAccountDirectory().getUserAccountList())
                    for(CoffeeRequest coffeeRequest : us.getCoffeeQueue().getCoffeeRequestList())
                        cq.getCoffeeRequestList().add(coffeeRequest);
        
        for(CoffeeRequest coffeeRequest : cq.getCoffeeRequestList())
            for(Coffee coffee : coffeeRequest.getCoffeeOrder().keySet()){
                int count = 0;
                if(coffeeRank.containsKey(coffee.getName()))
                    count = coffeeRank.get(coffee.getName());
                count = count + coffeeRequest.getCoffeeOrder().get(coffee);
                coffeeRank.put(coffee.getName(), count);
            }
        
        ArrayList<Map.Entry<String, Integer>> rankList = new ArrayList(coffeeRank.entrySet());
        
        Collections.sort(rankList, new Comparator<Map.Entry<String, Integer>>() {

            @Override
            public int compare(Map.Entry<String, Integer> o1, Map.Entry<String, Integer> o2) {
                return -o1.getValue()+o2.getValue();
            }
        });
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for(int i = 0; i< 5; i++){
            dataset.setValue(rankList.get(i).getValue(), "a", rankList.get(i).getKey());
        }
        JFreeChart chart = ChartFactory.createBarChart("Coffee Order", "Coffee Name", "Number", dataset, PlotOrientation.VERTICAL , false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame chartFrame = new ChartFrame("Most popular books", chart);
        chartFrame.setVisible(true);
        chartFrame.setSize(600, 400);
        
        
    }//GEN-LAST:event_popCoffeeButtonActionPerformed

    private void popBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popBookButtonActionPerformed
        // TODO add your handling code here:
        HashMap<String, Integer> bookRank = new HashMap();
        
        for(Book book : enterprise.getBookDirectory().getBookList()){
            bookRank.put(book.getName(), 0);
        }
        
        for(BookRequest bookRequest : enterprise.getBookQueue().getBookRequestList()){
            for(Book book : bookRequest.getBookList()){
                int count = 0;
                if(bookRank.containsKey(book.getName()))
                    count = bookRank.get(book.getName());
                count ++;
                bookRank.put(book.getName(), count);
            }
        }
        
        ArrayList<Map.Entry<String, Integer>> rankList = new ArrayList(bookRank.entrySet());
        
        Collections.sort(rankList, new Comparator<Map.Entry<String, Integer>>() {

            @Override
            public int compare(Map.Entry<String, Integer> o1, Map.Entry<String, Integer> o2) {
                return -o1.getValue()+o2.getValue();
            }
        });
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for(int i = 0; i< 5; i++){
            dataset.setValue(rankList.get(i).getValue(), "a", rankList.get(i).getKey());
        }
        JFreeChart chart = ChartFactory.createBarChart("Book Borrow", "Book Name", "Number", dataset, PlotOrientation.VERTICAL , false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame chartFrame = new ChartFrame("Most popular books", chart);
        chartFrame.setVisible(true);
        chartFrame.setSize(600, 400);
    }//GEN-LAST:event_popBookButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton popBookButton;
    private javax.swing.JButton popCoffeeButton;
    private javax.swing.JButton popStuButton;
    // End of variables declaration//GEN-END:variables
}
