/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.Student;

import Business.Book.BookDirectory;
import Business.Coffee.Coffee;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.LibraryEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.StudentOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CoffeeRequest;
import java.awt.CardLayout;
import java.util.HashMap;
import javax.swing.JPanel;

/**
 *
 * @author cyyo
 */
public class StudentWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel container;
    private UserAccount account;
    private StudentOrganization organization;
    private Enterprise enterprise;
    private Network network;
    private BookDirectory myLibrary;
    private EcoSystem ecoSystem;
    private HashMap<Coffee, Integer> cart;
    
    /**
     * Creates new form studentManagementJPanel
     */
    public StudentWorkAreaJPanel(JPanel container, UserAccount account, StudentOrganization organization, Enterprise enterprise, Network network, EcoSystem ecoSystem) {
        this.container = container;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;
        this.network = network;
        myLibrary = new BookDirectory();
        this.cart = new HashMap();
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        requestAppointTaBtn = new javax.swing.JButton();
        borrowBooksBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        checkHistoryButton = new javax.swing.JButton();
        orderCoffeeBtn = new javax.swing.JButton();
        ViewOrderBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        requestAppointTaBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        requestAppointTaBtn.setForeground(new java.awt.Color(102, 0, 255));
        requestAppointTaBtn.setText("Request an appointment with tutor");
        requestAppointTaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestAppointTaBtnActionPerformed(evt);
            }
        });

        borrowBooksBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        borrowBooksBtn.setForeground(new java.awt.Color(0, 102, 102));
        borrowBooksBtn.setText("Borrow your books");
        borrowBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowBooksBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Please select the service: ");

        jLabel3.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel3.setText("Have difficulites in studying?");

        jLabel4.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel4.setText("Want to read books?");

        checkHistoryButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        checkHistoryButton.setForeground(new java.awt.Color(0, 102, 102));
        checkHistoryButton.setText("Check Book History");
        checkHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkHistoryButtonActionPerformed(evt);
            }
        });

        orderCoffeeBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        orderCoffeeBtn.setForeground(new java.awt.Color(153, 0, 0));
        orderCoffeeBtn.setText("Order Coffee");
        orderCoffeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderCoffeeBtnActionPerformed(evt);
            }
        });

        ViewOrderBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ViewOrderBtn.setForeground(new java.awt.Color(153, 0, 0));
        ViewOrderBtn.setText("View Coffee Orders");
        ViewOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewOrderBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel5.setText("Want to order coffee?");

        jLabel2.setText("一 一 一 一 一 一 一 一 一 一 一 一 一  一 一 一 一 一 一 一 一 一 一 一 一 一 一 一 一 一");

        jLabel6.setText("一 一 一 一 一 一 一 一 一 一 一 一 一  一 一 一 一 一 一 一 一 一 一 一 一 一 一 一 一 一");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Images/stu.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkHistoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ViewOrderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(borrowBooksBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(orderCoffeeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(requestAppointTaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(requestAppointTaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(borrowBooksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addComponent(checkHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orderCoffeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addComponent(ViewOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void borrowBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowBooksBtnActionPerformed
        // TODO add your handling code here:
        BorrowBooksJPanel borrowBooksJPanel = new BorrowBooksJPanel(container, account,myLibrary, (LibraryEnterprise) enterprise);
        container.add("borrowBooksJPanel", borrowBooksJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_borrowBooksBtnActionPerformed

    private void checkHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHistoryButtonActionPerformed
        // TODO add your handling code here:
        BookHistoryViewJPanel bookHistoryViewJPanel = new BookHistoryViewJPanel(container, account, (LibraryEnterprise) enterprise);
        container.add("bookHistoryViewJPanel", bookHistoryViewJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_checkHistoryButtonActionPerformed

    private void orderCoffeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderCoffeeBtnActionPerformed
        // TODO add your handling code here:
        OrderCoffeeJPanel orderCoffeeJPanel = new OrderCoffeeJPanel(container, account, cart, network);
        container.add("orderCoffeeJPanel", orderCoffeeJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_orderCoffeeBtnActionPerformed

    private void requestAppointTaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestAppointTaBtnActionPerformed
        // TODO add your handling code here:
        MakeRequestJPanel makeRequestJPanel = new MakeRequestJPanel(container, account, (LibraryEnterprise) enterprise);
        container.add("makeRequestJPanel", makeRequestJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_requestAppointTaBtnActionPerformed

    private void ViewOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewOrderBtnActionPerformed
        // TODO add your handling code here:
        ViewOrderJPanel viewOrderJPanel = new ViewOrderJPanel(container, account);
        container.add("viewOrderJPanel", viewOrderJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_ViewOrderBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewOrderBtn;
    private javax.swing.JButton borrowBooksBtn;
    private javax.swing.JButton checkHistoryButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JButton orderCoffeeBtn;
    private javax.swing.JButton requestAppointTaBtn;
    // End of variables declaration//GEN-END:variables
}
